org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-create
addon_name=BlueMap Create Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-create-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=312744
accepted_jar_sha256=e9e860ff0a3cc3398090d03f36441a9df863ec96c0c5e6da408815a1f9c1cd05
